name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Change this if you're using another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/flask-ai-app:latest .
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/flask-ai-app:latest

      - name: Deploy to Azure Container Instance
        run: |
          az container create --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.ACI_NAME }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/flask-ai-app:latest \
            --cpu 2 --memory 4 \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label flask-ai-service \
            --ports 5000

      - name: Get Public URL
        run: |
          echo "Public URL: http://$(az container show --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.ACI_NAME }} --query ipAddress.fqdn --output tsv):5000"
